### ISSUE TITLE
[BUG] Extra cost not added to totals with onestepcheckout

### ISSUE THREAD

**Issue by JoostWan** [postnl/postnl-magento2#207]
**To Reproduce**
1. Use the onestepcheckout from Onestepcheckout.com
2. Add fee like €2 for evening delivery 
3. Select evening delivery 

**Expected result**
Totals are recalculated 

**Actual result**
Nothing happening. When you placed the order the final price is correct but custom don't see the 2 euro shipping fee at the checkout. 

**Screenshots**
![Screenshot 2020-10-05 at 11 56 50](https://user-images.githubusercontent.com/5435412/95065839-e0094e00-0701-11eb-93e0-ae835c997c46.png)

![Screenshot 2020-10-05 at 11 56 54](https://user-images.githubusercontent.com/5435412/95065852-e3043e80-0701-11eb-99d5-9bf49ebe4346.png)

**Please complete the following information**
- Magento version: 2.3.5-p2
- PHP version: 7.2
- TIG PostNL version: 1.9.4.1

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

Thanks for letting us know. Could you update the extension to the latest version and try again?
If the problem remains, I'll test it and see what I can do. As far as I know we don't have official support yet for that OSC.

Kind regards,
Jasper
TIG

**Comment by JoostWan** [comment]
@tig-jaspersmits With the latest version there problem still exist. Totals are not updated when you choose evening delivery with a fee of 2 euro.

**Comment by tig-jaspersmits** [comment]
@JoostWan ,

I will retest this for you tomorrow. Missed your comment.
I'll get back to you once I have more information.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
Hi @JoostWan ,

Was just able to reproduce. Placed it on our backlog.
There is still no official support for OSC though. But our team will do their best to find a solution.

Kind regards,
Jasper
TIG

**Comment by JoostWan** [comment]
Thanks @tig-jaspersmits 

I hop it can be fixed. The OSC from onestepcheckout.com i used a lot in Magento 2 projects. It wat also used a lot in M1 projects and for M1 there the was official support from the TIG PostNL module.

**Comment by tig-vincentthart** [comment]
Hello @JoostWan,

For now PostNL has decided to not support the OneStepCheckout at the moment. They might change this in the future, but for now we will close this issue.

Have a nice day!

Vincent
