### ISSUE TITLE
[QUESTION] GraphQl support

### ISSUE THREAD

**Issue by ghost** [postnl/postnl-magento2#213]
**Question**

Hello, 

We are working on a new PWA studio project. The client wants to use the TIG PostNL module. 
Did the Tig PostNL team already started with GraphQl implementation? Or are you aware of 3rd party modules that can?

If not we probably will create a TIG_PostNLGraphQl Module. Please let me know you thoughts. Then a can quote the client on the 'extra' work. 

Would be great i we could work together to make this happen and make this available to the community

Thanks

Derrick

**Comment by tig-jaspersmits** [comment]
Hi @dheesbeen ,

Thanks for creating this issue. I'll inform the developers and will get back to you with a response.

Kind regards,
Jasper
TIG

**Comment by paales** [comment]
I was thinking about how I'd like this to be implemented.

With the release of Magento 2.4 the new Store Pickup functionality is added: https://docs.magento.com/user-guide/shipping/shipping-in-store-delivery.html

From a frontend developer standpoint it would be nice if:

PostNL pickup locations are available through the same query as the local pickup locations: https://devdocs.magento.com/guides/v2.4/graphql/queries/pickup-locations.html

PostNL pickup locations can be selected with the setShippingAddress mutation: https://devdocs.magento.com/guides/v2.4/graphql/mutations/set-shipping-address.html?itm_source=devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=#example-usage

Some discussion how to implement this:
https://github.com/magento/inventory/issues/3235


https://github.com/magento/magento2/blob/632a7c61dfd6b2bda8159ed294543fcb9bbaa147/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L91-L95

**Comment by paales** [comment]
I was thinking about how I'd like this to be implemented. With the release of Magento 2.4 the new Store Pickup functionality is added ([docs](https://docs.magento.com/user-guide/shipping/shipping-in-store-delivery.html))

From a frontend developer standpoint it would be nice if PostNL pickup locations are available through the same [`pickupLocations` query](https://devdocs.magento.com/guides/v2.4/graphql/queries/pickup-locations.html) as the local pickup locations.

PostNL pickup locations can be selected with the [`setShippingAddress` mutation](https://devdocs.magento.com/guides/v2.4/graphql/mutations/set-shipping-address.html?itm_source=devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=#example-usage)

Adding additional input fields to the setShippingAddress can be easily achieved: [base implementation](https://github.com/magento/magento2/blob/632a7c61dfd6b2bda8159ed294543fcb9bbaa147/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L91-L95), [extension example](https://github.com/magento/inventory/blob/1.2-develop/InventoryInStorePickupQuoteGraphQl/etc/schema.graphqls#L9)

Related: https://github.com/magento/inventory/issues/3235

**Comment by tig-jaspersmits** [comment]
Hi @paales ,

Thanks for sharing this. I just noticed I didn't reply to this yet.. 
@tig-dennisvanderhammen could you take a look at this one?

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Yeah sure!

As for the actual implementation, we'll have to sit around the table with our development team to see how our endpoints will look like in a finished state.
We appreciate the ideas you're throwing at us @paales , we'll use that in our discussions. 

We definitely have GraphQL on our radar, and are eager to work on it as well. If we have any updates on this feature, we'll definitely post an update here!

**Comment by paales** [comment]
@tig-dennisvanderhammen If you need help or want feedback, dont hesitate to tag me and I'll try and chime in :)

**Comment by tig-jaspersmits** [comment]
I will close this issue since there is not much more information we can give about this topic right now.
When our team is looking for assistance in how to implement, we will let you know!

Kind regards,
Jasper
TIG

**Comment by lewisvoncken** [comment]
Heej @paales 

I understand but I would recommend to think about another option then using the Magento pickupLocations query because this will force you to use the Magento Multi Source Inventory Setup. Which in my opinion is not necessary for all the projects and is overhead if you have just a simpel webshop with one inventory.

@tig-dennisvanderhammen could you please take this in consideration?

**Comment by paales** [comment]
@lewisvoncken I believe MSI is replacing the legacy inventory system in Magento 2.5. I will ask Magento their expected timeline is.

**Comment by seansan** [comment]
Please dont close this issue. GraphQL is important, to work with many new solutions, one of which is HYVA. It needs to be on the roadmap!

**Comment by lewisvoncken** [comment]
It would be great if there would be a TIG separate PostNLGraphQl module. For now we have created our own module to add GraphQl support for PostNL.

**Comment by seansan** [comment]
+1

Can you share the extension you're referring to?

**Comment by HenrivantSant** [comment]
Hi Tig!

Can we get an update on the progress in the area? We're already waiting for some time to upgrade our customer's checkout to a headless app. We're waiting for a solution for TIG to start this process. 

Do you have a timeline for a GraphQl/REST API? Or is it already there and is it missing in the documentation?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @HenrivantSant ,

I don't have a timeline yet, it's on our long term backlog, I will add your message to the backlog item as an "upvote" of the feature. 
 If you wish to express your urge for the need for compatibility of the PostNL extension, the best thing to do is to send an e-mail to digitaleklantsupport@postnl.nl.

If you want to know the status of the backlog issue in the future you can contact us and ask about the status of POSTNLM2-1032, this is our internal issue number for GraphQl.

Have a great day,
Jeffrey

**Comment by lewisvoncken** [comment]
@seansan @HenrivantSant 

We have created an extension with GraphQL support, if you want I could share some insides about the module.

**Comment by rbnmulder** [comment]
@lewisvoncken we are currently exploring this functionality. 
Would you like to share some information about your module with me?

Much appreciated and thanks for the consideration.
