### ISSUE TITLE
Customer account implementation does not use StreetFields service

### ISSUE THREAD

**Issue by TechNick66** [postnl/postnl-magento2#257]
When a customer creates an account and wants to place an order she get the error 'straatnaam mag niet meer dan 1 regel bevatten'.
This looks to be related to an issue also reported at [https://github.com/tig-nl/postcode-magento2/issues/29 ](url)

The StreetFields service create the street field based on set configuration. The customer account implementation does not use this service and always returns a three item array in CustomerForm. We use the setting to store the address in one line so the form on customer/address/edit/id/1 returns an error "Adres" mag niet meer dan 1 regels bevatten..

**To Reproduce**
1 - Place a new order including the registration of a new account.
2 - Log out
3 - Login and place a new order and try to complete it.
3 - The error ''straatnaam mag niet meer dan 1 regel bevatten' is displayed

**Expected result**
The address is rendered normally.

**Actual result**
Application returns error 'straatnaam mag niet meer dan 1 regel bevatten'.

**Workaround**
None
When I create a new address via the backend with streetname and house number on one line and delete the wrong address registration the application works fine.
Note that  the house number is not shown on any of the lines in the backend when I try to edit the failing address. This is why I have to delete the incorrect registration.

**Screenshots**

** Please complete the following information**
- Magento version: 2.4.2
- PHP version: 7.4.11
- TIG PostNL version: 1.9.8

**Comment by tig-jeffreybranderhorst** [comment]
Hey @TechNick66 ,

Thank you for contacting us, we are going to investigate this further! Thank you!

Have a nice day,
Jeffrey

**Comment by raymondberkel** [comment]
Hey @TechNick66 and @tig-jeffreybranderhorst,

Is this issue solved or is there any fix? I have exact the same problem.

Magento version: 2.4.4
PHP version: 8.1
TIG PostNL version: 1.12.2

Regards,

Raymond

**Comment by tig-jeffreybranderhorst** [comment]
Hi @raymondberkel ,

This issue is still on our backlog, I have asked the team for a work-a-round and if you change the address settings to 2 lines it should work. This should be a work-a-round. But the initial issue is still on the backlog. 

Have a great day,
Jeffrey

**Comment by raymondberkel** [comment]
Thanks. 

Please let me know when a fix is available.

Regards,

Raymond

**Comment by tig-jeffreybranderhorst** [comment]
Hey Raymond,

We will inform you and update this github issue when it is fixed.

Have a great day,

Jeffrey

**Comment by JorisPostNL** [comment]
Hi Raymond,

This fix was released in our most recent update.

Kind regards,
Channel Integrations
PostNL
