### ISSUE TITLE
[QUESTION] How to deploy matrix rates on production

### ISSUE THREAD

**Issue by memen45** [postnl/postnl-magento2#268]
**Question**
On the developer device, the matrix rates were imported and tested. All works fine. Now the config is dumped and added to version control (git) and the following line can be found in the config:
```'matrixrate_import' => 'matrix-rates-postnl-tig.csv,application/vnd.ms-excel,/tmp/phpnFg91F,0,1368',``` 

On deploying this config in production, the matrix rates from development are not found and the rate is just flat. How can the matrix-rates file be carried over to the production server? Should this be done through the git repository?
Where will the module look for the file? I could not find the file back in the filesystem on the developer device.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45 ,

You need to re-upload the csv to the live server as well, so the matrix rates are uploaded to the database. If you are still having problems after this, what I don't expect but if you do please contact PostNL at digitaleklantsupport@postnl.nl

Have a great day,
Jeffrey

**Comment by memen45** [comment]
Thanks for your response. So on each deploy to production you have to
- (normal) `bin/magento app:config:dump system scopes`
- (extra) find the line `'matrixrate_import' => 'matrix-rates-postnl-tig.csv,application/vnd.ms-excel,/tmp/phpnFg91F,0,1368',` and remove it
- (normal) then add to git, run the deploy as usual
- (extra) login to admin, find the matrix rates csv and upload 

I will do this for now, however, these extra steps make the deployment process less smooth and more prone to errors. Also rollback is impossible, since the previous files cannot be restored. Could it be simplified?

Adding the tig/postnl matrix rates csv file to git, which is loaded on `bin/magento app:config:import` would be very nice and allow for zero downtime deployment.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @memen45 ,

Currently our module does not support the import of matrix rates through the config file, we would like to add this to our module, but that is going to go through the backlog and PostNL decides what is added to the extension, so this could take a while before it is really added to the extension. For now we would like to find a intermediate solution to get you up and running. Could you please elaborate on the deployment? For instance how do you update products, is this done through data patches?

Have a great day,
Jeffrey

**Comment by memen45** [comment]
Thanks for your response and great to hear you are looking into it! Applied the steps as stated in previous post, seemed to sort of work. Got some errors regarding configuration changed externally, so it was required to do app:config:import or setup:upgrade as well.

For products the UI is used (until I find a better way, as ideally I would like to update these through git as well). The deployment is done using [deployphp/deployer](https://github.com/deployphp/deployer/) tool with the magento2 recipe. This way the production server can be updated with zero downtime with the new config values and with the updated composer packages. 
Not sure how the csv could be safely transferred through git, I am not aware of other packages that do this with files. Maybe the app/code directory is safe? Or maybe storing json format (instead of csv) inside config.php is a solution.
