### ISSUE TITLE
[QUESTION] Confirm and Print Shipment label fails

### ISSUE THREAD

**Issue by memen45** [postnl/postnl-magento2#269]
First time trying to create the label, does not work. How can we debug this further? Logs inside `var/log/PostNL/` directory are all empty. Tried browser console, but no message in console and no requests to e.g. api.postnl.nl. Tried to watch the requests on the server, but also not a single request outgoing between pressing the button `Confirm and Print Shipment label` and receiving both errors.

![afbeelding](https://user-images.githubusercontent.com/27782135/133845092-3672ee53-d7fa-4c69-8619-6cfb78d86a73.png)

The shipment in this case should be a letterbox parcel extra: 
![afbeelding](https://user-images.githubusercontent.com/27782135/133845768-b8ab2483-3768-4d51-9853-160d84fa461e.png)

**Comment by memen45** [comment]
Okay I found the issue. The apikey is encrypted before it is stored in the config,php file. Since the Magento crypt key is unique per installation, the production server was not able to read the apikey properly. 

Workaround: I removed the apikey field from the config.php and then added it on production manually. However as mentioned in #268, this adds additional manual steps to the deploy process which can cause errors. Is there a proper way of deploying these config values from the development server to the production server?

**Comment by tig-mvonk** [comment]
Both this and issue #268 are related to the export of the configuration file. To keep these settings out of your `config.php` we could create a patch for you containing some changes to the `di.xml` preventing these configuration fields to be exported. This patch would be a short term solution, the long term solution is as my colleague described in ticket #268 up to PostNL.
