### ISSUE TITLE
[BUG] PostNL with custom shipping carrier not applying PostNL functions

### ISSUE THREAD

**Issue by dutchwebdesign** [postnl/postnl-magento2#277]
**To Reproduce**
1. Go to Stores > config > sales > PostNL
2. Click on extra settings > advanced settings > Add a custom shipping carrier
3. Go to Customers > All Customers 
4. Select a Customer and create order with the custom shipping carrier of step 2.
5. Ship order

**Expected result**
Get PostNL Print label, Print packaging slip in shipment 

**Actual result**
No PostNL functions are available

**Workaround**
None

**Screenshots**

![image](https://user-images.githubusercontent.com/40382854/140521605-d36dcd43-4113-41b2-b1f1-052ae9d21151.png)

as you see no PostNL Print label etc 
![image](https://user-images.githubusercontent.com/40382854/140521771-65ad2c24-d593-48ad-ace8-e8469649a521.png)

** Please complete the following information**
- Magento version: [e.g. Magento 2.4.3-p1]
- PHP version: [e.g. 7.4.0]
- TIG PostNL version: [e.g. 1.10]

**Comment by tig-jeffreybranderhorst** [comment]
Hey @dutchwebdesign ,

Thank you for submitting this! I just tested this and was able to reproduce it. I will place this on our backlog, so we can investigate this further and make a fix for it. I did find a workaround for now, if you go back to the order overview and select the order you just made and use the dropdown and select" PostNL - Make shipment and print labels" you will get the label.  This means as workaround, you can use the grid options to finish your PostNL order!
Thanks again for submitting this!

Have a great day,
Jeffrey

**Comment by dutchwebdesign** [comment]
Hi Jeffrey

Thanks for the fast reply. The workaround will work for now and we will see the fix in the future.

Cheers
vince
