### ISSUE TITLE
[BUG] Pickup point added as regular address

### ISSUE THREAD

**Issue by mlaurense** [postnl/postnl-magento2#284]
**To Reproduce**
1. Place an order as a guest, select a pickup point (I selected Laan oud-Indiëgangers 5 Rijssen)
2. After the order is placed, create an account using the button shown after checkout
3. The pickup point address is added as an additional address

**Expected result**
The pickup point address should not be visible as a standard address, as this allows the customer to ship a future order to the pickup point as a regular shipment.

**Actual result**
The address is added to the customer account and visible when placing a new order:
![Schermafbeelding 2021-12-13 om 11 20 20](https://user-images.githubusercontent.com/16759472/145795237-2ff62e30-dea0-4f29-8428-833a6600320d.png)

**Workaround**
None

** Please complete the following information**
- Magento version: 2.4.3-p1
- PHP version: 7.4
- TIG PostNL version: 1.10.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi @mlaurense,

Thank you for submitting this issue, we will test this and place the issue on the backlog if we can reproduce it. Thank you, for the clear steps to follow to reproduce it!

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @mlaurense,

We have tested this on our internal test environment and can reproduce this behavior. Thank you for your step to step guide, this really helped to reproduce the error.

I've placed this issue on our Backlog and will keep you informed of the progress.

Have a great day,
Jeffrey
