### ISSUE TITLE
[BUG] Pickup point not selected after re-order

### ISSUE THREAD

**Issue by chrisjansenvts** [postnl/postnl-magento2#291]
After re-ordering an existing Magento order placed with PostNL as shipping method the product code changes to default product code. So when the original order is a pickup order, the re-order is a regular order. But the shipping address is not changed to the customer address, but the address of the pickup point. Result is that a pickup-point receives an order without pickup information.

**To Reproduce**
1. Customer place an order with the pickup point option (code 3533)
2. As admin re-order this order and shipping method PostNL, shipping address is address of the pickup point;
3. Module assigned the regular shipping option instead of pickup point (code 3085);
4. Result is that the order will be shipped as an regular order to a pickup point;

**Expected result**
Copy the original product code to the created re-order.

**Actual result**
Re-order has code 3085 instead of code 3533 and is not an pickup order.

**Workaround**
None

** Please complete the following information**
- Magento version: Magento 2.4.3
- PHP version: 7.4
- TIG PostNL version: 1.10.1

**Comment by tig-jeffreybranderhorst** [comment]
Hi @chrisjansenvts,

Thank you for submitting this bug, with the steps to reproduce included. Because of this, we were able to reproduce it. I will create a backlog issue for this bug and together with PostNL we will make a plan to fix this issue.

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment]
Hi @janssensjelle,

Thank you for sharing the additional information. The issue is on the backlog, but it is not on the roadmap at the moment for the upcoming release. We will check if this can be added to one of the release after the next release.

Have a nice day!

Vincent
