### ISSUE TITLE
[FEATURE] Disable specific shipment days

### ISSUE THREAD

**Issue by watista** [postnl/postnl-magento2#325]
**Please rephrase the following line:**

As a ..certain type of user.. I'd like to ..describe what you want.. in order to ..write goal(s)..

**Suggestions and background**

If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

Hi,

I would like an option to disable specific shipment days so that customers cannot select this date as a shipment day option during the checkout process. We have a couple days in the year when we don't process orders, so the day after should not be an available option for customers to select as shipment day.

Thanks in advance!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @watista ,

I will place this on our backlog, because it would be a new feature, PostNL will decide if this will be added to the extension and when. I will place it on the backlog, so it will be not forgotten. 

Have a great day,
Jeffrey
