### ISSUE TITLE
[FEATURE] Make cargo pallet options available for matrix rate

### ISSUE THREAD

**Issue by rbouma** [postnl/postnl-magento2#334]
**Please rephrase the following line:**

As a shop manager I'd like to gives the customer an option in the checkout for if the total order weight is more than specified kg than the order is processed as one of the Cargo options specified in the matrix rate, shipping and delivery days in weekend is not available. Same as the postal office option need te be removed for cargo options.

![CleanShot 2022-09-28 at 08 07 33](https://user-images.githubusercontent.com/14012592/192700803-4d8d89e5-31b3-49ef-84a5-47997a42cc19.png)

Zo we have currently setup the matrix rate as follows:
```
NL,*,*,0.0000,0.0000,0,regular,5.5000,
NL,*,*,0.0000,0.0000,0,letterbox_package,2.9500,
NL,*,*,30.0000,0.0000,0,regular,49.5000,
```

so   if the total weight of the order is above 30kg the shipping amount will be 49.50 but this generate a problem because the customer can select delivery days in the weekend or postal office but that is not possible for a pallet delivery.

What we like to see is that cargo_options is made available in the matrix  rate so we can change as follow:
`NL,*,*,30.0000,0.0000,0,cargo_options_3610,49.5000,`
instead of using the regular package type.

So the code 3610 is used for Cargo Pallet NL and delivery days as in weekends + postal office should not available in the checkout if the total weight of the order.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @rbouma ,

Thank you for submitting this enhancement, I think it is a great idea. I will place this on our backlog so PostNL can also see this request, and they can then decide to implement in the extension. 

Have a great day,
Jeffrey
