### ISSUE TITLE
[QUESTION] Selecting alternative delivery when creating orders through Magento API

### ISSUE THREAD

**Issue by ThomasMW** [postnl/postnl-magento2#339]
In our Magento instance we have the setting for the alternative delivery 'Extra cover' when an order is above a specific amount. This works fine when using the store-front checkout. However I would like to be able to also use this alternative delivery when creating orders through the Magento API.

When adding the shipping information to an order using the Magento API you add to the following to the payload;

```
"shipping_method_code": "regular",
"shipping_carrier_code": "tig_postnl"
```

When creating orders through the API which have an amount higher than the threshold the alternative delivery isn't applied to the order.

Is it possible to simply replace the ```shipping_method_code``` with the alternative delivery and if so where can I find all available shipping method codes? I tried accessing the documentation but as of yet I haven't been granted access.

**Comment by tig-jeffreybranderhorst** [comment]
Hey @ThomasMW ,

The shipping_method_codes that there are available are: pakjegemak, extra@home, regular, letterbox_package.  Via the API you can also send along product codes, Product code 3087 is for extra cover. 

That the documentation is not available right now is correct, we are aware of this and working on it.  You can see all the API call in swagger if you want.

Have a great day,
Jeffrey

**Comment by ThomasMW** [comment]
Hi @tig-jeffreybranderhorst 

I used swagger to inspect the /shipping-information endpoint but I can't quite make out where the product code would go in the payload.

However I was using v1.12.1 of the extension and decided to update to v1.12.4. Now when accessing swagger the following error is logged;

```
[2022-11-10 14:51:50] main.CRITICAL: Report ID: webapi-636d10069ddbd; Message: The "MatrixrateInterface" class doesn't exist and the namespace must be specified. Verify and try again. {"exception":"[object] (Exception(code: 0): Report ID: webapi-636d10069ddbd; Message: The \"MatrixrateInterface\" class doesn't exist and the namespace must be specified. Verify and try again. at /data/web/magento2/vendor/magento/framework/Webapi/ErrorProcessor.php:208, LogicException(code: 0): The \"MatrixrateInterface\" class doesn't exist and the namespace must be specified. Verify and try again. at /data/web/magento2/vendor/magento/framework/Reflection/TypeProcessor.php:143)"} []
```

I verified this by rolling back to v1.12.1 and then testing swagger, then updating to v1.12.3 and testing again. On those versions I can use swagger without the described issue.

We are on Magento 2.4.2-p2 Open Source.

Since I can't access the documentation would you either care to tell me where to add the product code to the shipping information or see if you can reproduce the issue described above?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ThomasMW ,

When creating a Magento Shipment you also need to create a PostNL shipment.
This is done after the shipment has been created.

Once using an API key in swagger that has rights to see everything.
You can see the tIGPostNLShipmentManagementV1
In here you have the /v1/postnl/shipment/{shipmentId}/createShipment
here you van give { ‘productCode’: 0, ‘colliAmount’: 0 }
In here you van add the correct product code that you want to use and also the colli amount
In your case you would use 3087 as the product code. This is the code for Extra Cover.

Hope the explanation of my colleague helps you further! 

Have a great day,
Jeffrey

**Comment by ThomasMW** [comment]
Are we talking about the same type of shipment?

Using the endpoint /shipping-information is not for creating a shipment, but for adding the shipping information during the order creation.

Our Magento instance is connected to the PostNL Integrator from PostNL Fulfilment (a seperate division within PostNL). The orders are exported to the PostNL Integrator by XML and these XML files contain the product code so that the Integrator and therefor the warehouse knows how to ship the items to the customer. However, up until this moment no Magento shipment has been created. The shipment is only created when the Integrator tells Magento the order has been fully shipped.

Which means I need to assign a product code to the order before it is exported to the Integrator.

I would assume I need to create, or perhaps edit, a PostNL order which is stored in the table tig_postnl_order. I see these orders can by accessed at ```/V1/postnl/orders```. Is this what you are referring to?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @ThomasMW ,

I have placed this on our backlog because we found out that there is an issue with an after method on the save.  Because of this issue, the methods like extra cover won't be passed on to the backend. 

We are going to investigate this further and make a fix in a future release, thank you for submitting this. 

Have a great day,
Jeffrey

**Comment by ThomasMW** [comment]
Hi @tig-jeffreybranderhorst 

Any progress regarding this issue?

**Comment by tig-vincentthart** [comment]
Hi @ThomasMW,

It is on our backlog to be picked up, but it hasn't been resolved yet. 

When we have a solution, we will check if we can share a patch with you before the release.

Have a nice day,
Vincent

**Comment by ThomasMW** [comment]
So we're closing on this issue being almost a year old. Is there any progress or eta available on when this will be resolved?

**Comment by JorisPostNL** [comment]
Hi @ThomasMW, unfortunately we do not have the space to include this feature on our roadmap at this moment due to ongoing development in other areas. We will keep this on our backlog for future development once there is more room on our roadmaps.

Kind regards
Joris
PostNL Support

**Comment by ThomasMW** [comment]
Understood, thanks for getting back to me.
