### ISSUE TITLE
[QUESTION] Why storing PDF labels in database?

### ISSUE THREAD

**Issue by i6media** [postnl/postnl-magento2#340]
**Question**
We noticed that the entire PDF of a label is stored in the tig_postnl_shipment_label SQL table.
Storing binary or base64 in databases is usually considered bad practice.

Our database is growing rapidly in size due to this matter.
Wouldn't it be better to store the labels in the var folder of Magento 2 instead of in the DB itself?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @i6media ,

Thank you for submitting this issue, I will place this on our backlog so PostNL together with our developers can have a look at this and change it. 

Have a great day,
Jeffrey

**Comment by i6media** [comment]
Hi Jeffrey,

Thank you for the reply. I agree that labels are only a few kb, yet they are being loaded in the server's memory instead of on its harddrive. Memory is much more expensive than disk-size. If the DB grows over time (e.g. a few years), the few KB's are going to add up which makes it much better to store the files on the servers HDD/SSD, instead of loading it into the memory.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @i6media ,

You are completely right that memory is more important than disk space.  I'm making sure your messages are also placed on our backlog in the same issue, so when we are going to discuss it, your points will be taking along with it. 

Have a great day and thank you once again!
Jeffrey

**Comment by mlaurense** [comment]
This is way more than 'a few KB'...
![Schermafbeelding 2023-05-04 om 15 45 52](https://user-images.githubusercontent.com/16759472/236225209-a1a21c60-d7a0-4d7e-b171-d7d7f388f2cc.png)
This table contains 104,077 rows with mainly old label data...

**Comment by sedero** [comment]
We have the same issue, 5,2GB of label entries in the database... for 104k shipment orders. Might be better to clean up old labels or store them somewhere else.

**Comment by Jeroen-Buro210** [comment]
Hi,

Any news on when this issue is looked at? We have the same problem, with a database table over 10GB. If it's not looked at soon, is there something we can do to temporarily fix this? Can I purge rows safely or is there going to be issues after that?

**Comment by JorisPostNL** [comment]
Hi Jeroen-Buro21,

Version 1.12.9 includes a change that ensures the label database will not continue to grow infinitely, but will overwrite earlier entries in the table at a certain point. If you would like to further decrease the size of the database we advise running an Optimize Table, which will essentially defragment the table clearing up space that is not used at that point.

**Comment by i6media** [comment]
Still think that it's bad practice to store binary data in MySQL, which is in this case completely unnecessary. Why aren't labels stored in the pub/media/postnl directory for example?

**Comment by JorisPostNL** [comment]
Hi i6media,

Thank you for your feedback. We will discuss the matter of storing labels and if we come up with another solution we will place that on the backlog for future developing.

Kind regards
Team Channel Integrations
PostNL

**Comment by i6media** [comment]
On the backlog again? To be fair, I created this issue almost a year ago...

> Wouldn't it be better to store the labels in the var folder of Magento 2 instead of in the DB itself?

There are many developers experiencing the same issue here.

**Comment by JorisPostNL** [comment]
Hi i6media,

The initial reporting of this issue resulted in the implementation of an automatic cleanup of the labels in the database, ensuring that it will not grow beyond a certain point, which was released in July this year. Based on the feedback we receive in this thread we will re-assess this fix and explore other options which might better suit the wishes of our customers.

Kind regards,
Team Channel Integrations
PostNL
