### ISSUE TITLE
[QUESTION] Wrong delivery date when choosing At the first opportunity

### ISSUE THREAD

**Issue by JSeverein** [postnl/postnl-magento2#363]
Hi, 

We have the Delivery days option Activated with a maximum number of 7 days. So the customers are able to select their own delivery date / time in the checkout.

We have received complaints from customers claiming that they did not see times but selected "At first opportunity", but when we check their orders we see a delivery date further in the future than expected. According to our customer service this happens regularly.

We expect that this fallback would use the next working day. But we see examples where the delivery date is 5-7 working days later. (f.e. an order created on 05/05, delivered at 12/05) This date is stored in the tig_postnl_order table with a expected_delivery_time_start and end as well.

I believe in case of a fallback it uses: $this->checkoutSession->getPostNLDeliveryDate() which should be filled by the DeliveryDate response from the calculate/date SOAP call to PostNL?

Is it possible the PostNL API returns a date this far in the future when the fallback option is chosen?

**Comment by JorisPostNL** [comment]
Hi JSeverein,

Thank you for bringing this issue to our attention. It was fixed in an earlier update.

Kind regards
Team Channel Integrations
PostNL
