### ISSUE TITLE
[BUG] compile error unexpected 'static' (T_STATIC)

### ISSUE THREAD

**Issue by GuidoHub** [postnl/postnl-magento2#366]
When running setup:di:compile after installing the latest version 1.12.9 you will get a compile error when running PHP version lower then 8 because in file Config\Model\Backend\DeliveryDateOff.php on row 88 you use static as return method for the function. This is only available from PHP 8 and higher.

**To Reproduce**

**Expected result**
No error when running PHP 7.X

**Actual result**
unexpected 'static' (T_STATIC)

**Workaround**
Chaning file manually

** Please complete the following information**
- Magento version: 2.4.5-p3
- PHP version: 7.4.x
- TIG PostNL version: 1.12.9

**Comment by JorisPostNL** [comment]
Hi GuidoHub,

This issue was fixed in the V1.12.9.1 release.

Kind regards
Team Channel Integrations
PostNL
