### ISSUE TITLE
[QUESTION] Who is maintaining this repo?

### ISSUE THREAD

**Issue by ThomasMW** [postnl/postnl-magento2#369]
Hi all,

I've noticed that issues are being flat out ignored for a while (months) now. Is this repo still being maintained and if so, by who?

**Comment by JorisPostNL** [comment]
Hi ThomasMW,

Until a short while ago the Github-tickets were forwarded to the developers and, where possible, fixes were developed and released for the issues reported and noted on the changelog. We noticed this does not provide enough information to our customers so going forward we will start actively responding to these tickets too again.

Kind regards
Team Channel Integrations
PostNL
