### ISSUE TITLE
[BUG] Product code 4952 removed, but still default

### ISSUE THREAD

**Issue by markvds** [postnl/postnl-magento2#370]
Product code 4952 has been removed from the available products here:
https://github.com/postnl/postnl-magento2/commit/2f3c5fbfdbb4f54e728c1b99e65b65b5db6eac67#diff-7d57a09e5cfef4ab6d275194daa780028d59c3f83768fb6b4eefefe8b4f4093b

But it's still set as default in `config.xml` for the 'Default EU delivery' option:
https://github.com/postnl/postnl-magento2/blob/master/etc/config.xml#L61

This leads to problems when generating barcodes. When the product code was removed, the default should also have been changed and a data patch should have been added that changed the setting if it was set to a non supported product code.

**Comment by JorisHoyle** [comment]
Hi Markvds,

Thank you for bringing this to our attention. We will release a new update soon which will include a fix for this issue.

Kind regards
Team Channel Integrations
PostNL
