### ISSUE TITLE
[FEATURE] Add flag $forceMagento during generate packingslip

### ISSUE THREAD

**Issue by yaroslav-qlicks** [postnl/postnl-magento2#374]
As a admin user I'd like to generate packingslip magento even xtento or fooman modules enabled and compatibility working

I suggest to add extra flag to method signature with default value to keep back compatibility
```php
\TIG\PostNL\Service\Shipment\Packingslip\GetPackingslip::get($shipmentId, $withLabels = true, $confirm = true, $forceMagento = false)
```
In this case in my own module I  can set $forceMagento = true and generate magento pdf even when xtento or fooman present
because now there are no option to control this

**Comment by JorisPostNL** [comment]
Hello @yaroslav-qlicks, thank you for bringing this to our attention. We have developed a fix for this issue and will release this as soon as possible. 

Kind regards
Joris
PostNL Support

**Comment by JorisPostNL** [comment]
Hi @yaroslav-qlicks, this change has now been deployed

Kind regards
Joris
PostNL Support
