### ISSUE TITLE
Pickup location Delivery Date Check

### ISSUE THREAD

**Issue by kaplansin** [postnl/postnl-magento2#376]
**To Reproduce**
1. Add Item into your cart, 
2. Go to checkout,
3. Select PostNL as shipping
4. Select Pickup location.
5. Finalize the order.
6. Create an other quote.
7. Goto Checkout
8. Select PostNL as shipping
9. Select Pickup location.
10. /postnl/deliveryoptions/save request will fail.

**Expected result**
/postnl/deliveryoptions/save must return 'ok' and Order shipping address must selected Pickup location address.

**Actual result**
 /postnl/deliveryoptions/save fails with 500 Internal Server Error. 
And Order will not have Pickup location address as Shipping address.

**Workaround**
Logout and Login and continue payment processes.

** Please complete the following information**
- Magento version: 2.4.6-p3
- PHP version: PHP 8.1.4
- TIG PostNL version: 1.13.0

**Comment by DarthFly** [comment]
Hi @kaplansin 
We tried to reproduce it but were not able to do this for now. Could you be able to try to reproduce this issue on https://public.postnlmagento2.hypernode.io ? If it's reproduced - please give us the first order number that you placed before error 500.

Your PR does makes sense, but it seems like the reason why the "date" is empty should go from the incorrect response in the first place and we would like to see why it ends up that way.
