### ISSUE TITLE
[BUG] Bulk printing PDF attachements not working. keeps loading untill php timeout limit is reached (even if you make it 4000 seconds) which makes no sense.

### ISSUE THREAD

**Issue by BlueRayNL** [postnl/postnl-magento2#379]
**To Reproduce**
1. Go to 'shipments tab in magento'
2. Click on 'bulk select 20 orders.'
3.  in the action menu click on PDF-shipments

**Expected result**

Bulk document of PDF's with all 20 shipments.

**Actual result**
Keeps loading infinitly.

**Workaround**
NONE

**Screenshots**
![image](https://github.com/postnl/postnl-magento2/assets/36154801/c82ea2f5-2285-4818-81c0-480ca30c7f8d)

** Please complete the following information**
- Magento version: 2.4.2
- PHP version: 7.4.33
- TIG PostNL version: 1.13.1

**Comment by BlueRayNL** [comment]
can someone reply from tig ????

**Comment by JorisPostNL** [comment]
Hi @BlueRayNL, thank you for your inquiry.

Kindly note the function you are referring to is native to Magento 2 and not handled by our plug-in. To be sure our plug-in isn't factoring in in an unexpected way we tried to reproduce the issue following the steps you note and received PDF containing 20 pages of packing slips within a few seconds without any problems. If you have seen any signs on your side that our plug-in is somehow involved in this issue we'll gladly look into this again.

Kind regards, and good luck,
PostNL Support
