### ISSUE TITLE
Incorrect / missing shipment type product codes [v1.13.0 and v1.13.1]

### ISSUE THREAD

**Issue by ThomasMW** [postnl/postnl-magento2#382]
With version 1.13.0 and 1.13.1 we're seeing 'non-set' shipment type product codes for specific destinations. For example when placing an order to Switzerland the product code '0_GP' is created. When we place an order for Germany the product code is indeed set to '04952_EPS' but the shipment type is not shown on the order grid.

**To Reproduce**
1. Place order
2. Set destination country to Germany / Switzerland
3. Complete payment so order goes to 'Processing'

**Expected result**
Correct product codes for shipment type

**Actual result**
Non-set shipping type product code and / or shipment type not shown in order grid.

**Workaround**
None

**Screenshots**
![Screenshot from 2024-03-18 18-45-20](https://github.com/postnl/postnl-magento2/assets/47826277/3f456049-4323-44fd-9e76-7dd6eaebf3f7)

** Please complete the following information**
- Magento version: Magento 2.4.4-p3
- PHP version: 7.4
- TIG PostNL version: 1.13.0 and 1.13.1

**Comment by JorisPostNL** [comment]
Hi @ThomasMW, thank you for bringing this to our attention. Could you please fill in the webform at https://developer.postnl.nl/support/form/ so our support team can analyse the problem?

**Comment by JorisPostNL** [comment]
Thank you, our support team will contact you as soon as possible!

**Comment by JorisPostNL** [comment]
@ThomasMW I think I found your webform inquiry in our system, but it is missing an e-mail address with which our support team can reach you. Could you provide your e-mail address so I can add it to the support case?

**Comment by ThomasMW** [comment]
@JorisPostNL You can reach me at thomas@treeofinformation.nl. I did receive the confirmation email though, case number 25709588.

**Comment by JorisPostNL** [comment]
Perfect, thank you! I have added it to the case so feel free to remove your comment if you prefer not to leave your e-mail address on this board.
