### ISSUE TITLE
[BUG] Printing packing slips throws an exception

### ISSUE THREAD

**Issue by Webwijs** [postnl/postnl-magento2#383]
Print packing slips gives error

**To Reproduce**
1. Go to a shipment in the Magento 2 admin
2. Click on PostNL - Print packing slip

![image](https://github.com/postnl/postnl-magento2/assets/151923490/e6906b58-6708-4e52-9692-6239893f11c5)

**Expected result**
The packing slip files are downloaded.

**Actual result**
> Error: Call to a member function getLabelFileFormat() on string in /****/vendor/tig/postnl-magento2/Controller/Adminhtml/PdfDownload.php:213

**Workaround**
Add `!is_string($label)` to the if-clause: 

`if (!is_string($label) && $label->getLabelFileFormat() !== LabelTypeSettings::TYPE_PDF) `

**Screenshots**

- Magento version: Magento 2.4.6-p4
- PHP version: 8.1.18
- TIG PostNL version: 1.14.0

**Comment by JorisPostNL** [comment]
Hi @Webwijs,

Thank you for bringing this to our attention. We are aware of this bug, and are currently working on a hotfix to solve this problem. We hope to release this hotfix soon.

Kind regards
Joris
PostNL Support
