### ISSUE TITLE
[BUG] Incorrect date option is selected for delivery after reloading the checkout page

### ISSUE THREAD

**Issue by YachYaroslav** [postnl/postnl-magento2#389]
**To Reproduce**
1. Go to 'Admin' -> 'Stores' -> 'Configuration' -> 'Sales' -> 'PostNL'
2. Open 'Delivery' -> 'Delivery Days' config section and set 'Maximum number of delivery days' to **14** (instead of 7 default).
3. Save config and clear the caches.
4. Go to frontend checkout page.
5. Fill the address of the Netherlands (e.g. Street Address - Weena XXXX, City - Rotterdam, Zip/Postal Code - 3013AL).
6. Click on 'PostNL' shipping method and select Monday (the earliest one / top one).
7. Refresh the checkout page (F5).
8. Scroll down to 'PostNL' shipping method.

**Expected result**
The same date option is selected (Monday 12-08-2024).

**Actual result**
The week after date option is selected (Monday 19-08-2024).

**Workaround**
None

**Screenshots**

Before reload (Monday 12-08-2024 is selected):

![monday-selected-before-reload](https://github.com/user-attachments/assets/2dfc10b1-e0e4-4a2d-8d38-7ceaa9d3cb74)

After reload (incorrect Monday 19-08-2024 is selected):

![incorrect-monday-selected-after-reload](https://github.com/user-attachments/assets/f9485b64-e573-41b5-a61d-e0ff9a770862)

- Magento version (pure with only tig/postnl-magento2): 2.4.6
- PHP version: 8.1.3
- TIG PostNL version: 1.15.2

---

Also the same issue is reproducible on a highly customized Magento (with Swissup_Firecheckout and many custom modules):

- Magento version: 2.4.3-p3
- PHP version: 7.4.28
- TIG PostNL version: 1.15.2

**Comment by YachYaroslav** [comment]
@JorisPostNL I don't agree with you. The bug is clearly on your side. You have to add `option.date === value.date` to `getPreviousDay` function in Delivery.js file. Please, reopen the ticket and fix that.

**Comment by YachYaroslav** [comment]
@JorisPostNL this is reproducible also without reloading the page (if you change the address for example). Comparing by day of the week is not enough for matching the correct option if you have more than 7 days available for the delivery.

**Comment by JorisPostNL** [comment]
Hi @YachYaroslav we will create a backlog ticket for this issue and will reconsider development if we demand for this change grows.

Kind regards
Joris - PostNL

**Comment by JorisPostNL** [comment]
Hi @YachYaroslav, we are currently working on the fix you suggested. This will be released after the current release we are working on, which will be done later this week. 

Kind regards
Joris - PostNL

**Comment by YachYaroslav** [comment]
Hi @JorisPostNL, glad to read that! Thanks!
