### ISSUE TITLE
[BUG] Please summarize your bug issue here

### ISSUE THREAD

**Issue by albundy2** [postnl/postnl-magento2#396]
To Reproduce

Go to checkout and fill in zipcode and housenumber
Address is shown and house number is shown
Finish the checkout and in the order e-email and backend admin the housenumber at the shipping address is missing again

Expected result
Housenumber is shown in mail and backend at orders

Actual result
Because the shipping house number is missing all Riverty payment options are rejected. And if we forget to fill it in before creating shipping labels the tracking code for PostNL isn't working.

Workaround
Turning off address / Postcode check in the PostNL plugin solves the problem.

** Please complete the following information**

Magento version: 2.4.6p3
PHP version: 8.1
PostNL 1.16
Extra information:
This problem was there before in an older version, but was solved and now in version 1.16 I have the same problem again.
The Housenumber is only missing in the shipping address, Billing address is complete

**Comment by JorisPostNL** [comment]
@albundy2 Thank you for bringing this to our attention. We would like to invite you to fill in the inquiry form at https://developer.postnl.nl/support/form/ so our colleagues from tech support can investigate the issue for you. If necessary they will forward the results to the development team for further investigation or repairing activities.

Kind regards
Joris - PostNL
